# Generated by Django 4.2.5 on 2023-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("01", "TODO"), ("02", "DOING"), ("03", "DONE")],
                default="01",
                max_length=2,
            ),
        ),
    ]
