# Generated by Django 4.2.5 on 2023-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_alter_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
