# Generated by Django 4.2.5 on 2023-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("01", "Todo"), ("02", "Doing"), ("03", "Done")],
                default="01",
                max_length=2,
            ),
        ),
    ]
